name: Bug report
description: Report a reproducible bug in DialogForge.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Tag, commit SHA, or local branch.
      placeholder: v0.1.0
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + Python version.
      placeholder: macOS 15.3, Python 3.12
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config excerpt
      description: Paste a minimal config snippet (remove secrets).
      render: yaml
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Include exact commands used.
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or traceback
      render: text
    validations:
      required: true
